- project-template:
    name: check-requirements
    check:
      jobs:
        - requirements-check
    gate:
      jobs:
        - requirements-check

- job:
    name: requirements-check
    parent: unittests
    required-projects:
      - openstack/requirements
