- project-template:
    name: check-requirements
    check:
      jobs:
        - requirements-check
    gate:
      jobs:
        - requirements-check

- job:
    name: requirements-cross-test
    parent: openstack-tox

- job:
    name: requirements-cross-nova-py27
    parent: requirements-cross-test
    required-projects: nova

- job:
    name: requirements-check
    parent: unittests
    required-projects:
      - openstack/requirements
    files:
      - ^tools/.*-requires$
      - ^.*requirements.txt$
      - ^.*requirements-py[2,3].txt$
      - playbooks/requirements-check.yaml

- project:
    name: openstack/requirements
    check:
      jobs:
        - requirements-cross-nova-py27
