- project-template:
    name: check-requirements
    check:
      jobs:
        - requirements-check
    gate:
      jobs:
        - requirements-check

- job:
    name: requirements-check
    parent: unittests
    required-projects:
      - openstack/requirements
    files:
      - ^tools/.*-requires$
      - ^.*requirements.txt$
      - ^.*requirements-py[2,3].txt$
      - playbooks/requirements-check.yaml

- job:
    name: cross-nova-func
    parent: openstack-tox
    run: playbooks/cross-nova-func/run
    post-run: playbooks/cross-nova-func/post
    timeout: 3000
    required-projects:
      - openstack/requirements
      - openstack/nova
