- project:
    templates:
      - openstack-pypy-jobs-nonvoting
      - publish-openstack-sphinx-docs
      - openstack-python-jobs
      - openstack-python35-jobs
    check:
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-trusty:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-bindep:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            voting: false
        - requirements-tox-py27-check-uc
        - requirements-tox-py35-check-uc:
            branches: ^(?!stable/(newton|ocata|pike)).*$
        - requirements-tox-validate-projects
        - cross-cinder-py27
        - cross-cinder-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-glance-py27
        - cross-glance-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-horizon-py27
        - cross-horizon-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-keystone-py27
        - cross-keystone-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-neutron-py27
        - cross-neutron-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-nova-py27
        - cross-nova-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-nova-functional
        - cross-swift-py27
        - cross-swift-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - requirements-integration
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      queue: integrated
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-trusty:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-py27-check-uc
        - requirements-tox-py35-check-uc:
            branches: ^(?!stable/(newton|ocata|pike)).*$
        - requirements-tox-validate-projects
        - cross-cinder-py27
        - cross-cinder-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-glance-py27
        - cross-glance-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-horizon-py27
        - cross-horizon-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-keystone-py27
        - cross-keystone-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-neutron-py27
        - cross-neutron-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - cross-nova-py27
        - cross-nova-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-functional
        - cross-swift-py27
        - cross-swift-py35:
            branches: ^(?!stable/(newton|ocata)).*$
        - requirements-integration
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    post:
      jobs:
        - publish-loci-requirements
    periodic:
      jobs:
        - publish-wheel-mirror-centos-7
        - publish-wheel-mirror-ubuntu-bionic
        - publish-wheel-mirror-ubuntu-trusty
        - publish-wheel-mirror-ubuntu-xenial
        - release-wheel-mirror:
            dependencies:
              - publish-wheel-mirror-centos-7
              - publish-wheel-mirror-ubuntu-bionic
              - publish-wheel-mirror-ubuntu-trusty
              - publish-wheel-mirror-ubuntu-xenial
    experimental:
      jobs:
        - legacy-tempest-dsvm-neutron-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full-opensuse-423:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

