- project:
    check:
      jobs:
        - requirements-tox-py38-check-uc-no-wheels
        - requirements-tox-py39-check-uc-no-wheels
        - requirements-tox-py310-check-uc-no-wheels
        - requirements-tox-py311-check-uc-no-wheels
