- project:
    name: openstack/requirements
    periodic:
      jobs:
        - build-wheel-mirror
        - release-wheel-mirror:
            dependencies:
              - build-wheel-mirror
        - propose-updates:
            vars:
              update_target: requirements-constraints
    templates:
      - system-required
      - openstack-pypy-jobs-nonvoting
      - publish-openstack-sphinx-docs
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-to-pypi
    check:
      jobs:
        - build-openstack-sphinx-docs:
            branches: master
        - legacy-requirements-integration-dsvm-ubuntu-trusty:
            branches: ^stable/newton$
        - legacy-requirements-integration-dsvm
        - legacy-requirements-tox-babel:
            files:
              - ^babel-test/.*
              - ^tox.ini
              - ^upper-constraints.txt
        - legacy-requirements-tox-py27-check-uc:
            files: ^upper-constraints.*txt$
        - legacy-requirements-tox-py35-check-uc:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            files: ^upper-constraints.*txt$
        - openstack-tox-validate
        - legacy-requirements-tox-validate-projects:
            branches: master
        - legacy-grenade-dsvm-neutron-multinode:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - cross-cinder-py27:
            files: ^upper-constraints.txt$
        - cross-cinder-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-glance-py27:
            files: ^upper-constraints.txt$
        - cross-glance-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-horizon-py27:
            files: ^upper-constraints.txt$
        - cross-horizon-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-keystone-py27:
            files: ^upper-constraints.txt$
        - cross-keystone-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-neutron-py27:
            files: ^upper-constraints.txt$
        - cross-neutron-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-py27:
            files: ^upper-constraints.txt$
        - cross-nova-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-functional:
            files: ^upper-constraints.txt$
        - cross-swift-py27:
            files: ^upper-constraints.txt$
        - cross-swift-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - legacy-tempest-dsvm-neutron-full:
            branches: ^(?!driverfixes/).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-grenade-dsvm-neutron:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      queue: integrated
      jobs:
        - build-openstack-sphinx-docs:
            branches: master
        - legacy-requirements-integration-dsvm-ubuntu-trusty:
            branches: ^stable/newton$
        - legacy-requirements-integration-dsvm
        - legacy-requirements-tox-babel:
            files:
              - ^babel-test/.*
              - ^tox.ini
              - ^upper-constraints.txt
        - legacy-requirements-tox-py27-check-uc:
            files: ^upper-constraints.*txt$
        - legacy-requirements-tox-py35-check-uc:
            branches: ^(?!stable/(newton|ocata|pike)).*$
            files: ^upper-constraints.*txt$
        - openstack-tox-validate
        - legacy-requirements-tox-validate-projects:
            branches: master
        - legacy-grenade-dsvm-neutron-multinode:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - cross-cinder-py27:
            files: ^upper-constraints.txt$
        - cross-cinder-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-glance-py27:
            files: ^upper-constraints.txt$
        - cross-glance-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-horizon-py27:
            files: ^upper-constraints.txt$
        - cross-horizon-py35:
            files: ^upper-constraints.*txt$
        - cross-horizon-py27:
            files: ^upper-constraints.*txt$
        - cross-horizon-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-keystone-py27:
            files: ^upper-constraints.txt$
        - cross-keystone-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-neutron-py27:
            files: ^upper-constraints.txt$
        - cross-neutron-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-py27:
            files: ^upper-constraints.txt$
        - cross-nova-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-functional:
            files: ^upper-constraints.txt$
        - cross-swift-py27:
            files: ^upper-constraints.txt$
        - cross-swift-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - legacy-tempest-dsvm-neutron-full:
            branches: ^(?!driverfixes/).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-grenade-dsvm-neutron:
            branches: ^(?!stable/newton).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    post:
      jobs:
        - propose-updates:
            vars:
              update_target: requirements
    experimental:
      jobs:
        - legacy-tempest-dsvm-neutron-pg-full:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full-opensuse-423:
            voting: false
            branches: ^(?!stable/(newton|ocata)).*$
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
