- project:
    check:
      jobs:
        - build-wheel-mirror-centos-7:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-bionic:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-trusty:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
            files:
              - bindep.txt
        - openstack-tox-validate:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
        - requirements-tox-babel:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
        - requirements-tox-bindep:
            voting: false
        - requirements-tox-py27-check-uc:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
        - requirements-tox-py35-check-uc:
            vars:
              pypi_mirror: "http://{{ zuul_site_mirror_fqdn }}:8080/pypi/simple/"
        - requirements-tox-py36-check-uc:
            voting: false
        - requirements-tox-validate-projects
        - cross-cinder-py27
        - cross-cinder-py35
        - cross-glance-py27
        - cross-glance-py35
        - cross-horizon-py27
        - cross-horizon-py35
        - cross-keystone-py27
        - cross-keystone-py35
        - cross-neutron-py27
        - cross-neutron-py35
        - cross-nova-py27
        - cross-nova-py35
        - cross-nova-functional
        - cross-osc-build-sphinx-docs
        - cross-swift-py27
        - cross-swift-py35
        - openstack-tox-py36
    gate:
      queue: integrated
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-trusty:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-py27-check-uc
        - requirements-tox-py35-check-uc
        - requirements-tox-validate-projects
        - cross-cinder-py27
        - cross-cinder-py35
        - cross-glance-py27
        - cross-glance-py35
        - cross-horizon-py27
        - cross-horizon-py35
        - cross-keystone-py27
        - cross-keystone-py35
        - cross-neutron-py27
        - cross-neutron-py35
        - cross-nova-py27
        - cross-nova-py35:
            files: ^upper-constraints.txt$
        - cross-nova-functional
        - cross-osc-build-sphinx-docs
        - cross-swift-py27
        - cross-swift-py35
        - openstack-tox-py36
