- project:
    templates:
      - openstack-pypy-jobs-nonvoting
      - openstack-python-jobs
      - openstack-python35-jobs
    check:
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-trusty:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-bindep:
            voting: false
        - requirements-tox-py27-check-uc
        - requirements-tox-py35-check-uc
        - requirements-tox-py36-check-uc:
            voting: false
        - requirements-tox-validate-projects:
            voting: false
        - cross-cinder-py27
        - cross-cinder-py35
        - cross-glance-py27
        - cross-glance-py35
        - cross-horizon-py27
        - cross-horizon-py35
        - cross-keystone-py27
        - cross-keystone-py35
        - cross-neutron-py27
        - cross-neutron-py35
        - cross-nova-py27
        - cross-nova-py35
        - cross-nova-functional
        - cross-osc-build-sphinx-docs
        - cross-swift-py27
        - cross-swift-py35
        - openstack-tox-py36
        - requirements-integration
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - build-wheel-mirror-centos-7:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-trusty:
            files:
              - bindep.txt
        - build-wheel-mirror-ubuntu-xenial:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-py27-check-uc
        - requirements-tox-py35-check-uc
        - cross-cinder-py27
        - cross-cinder-py35
        - cross-glance-py27
        - cross-glance-py35
        - cross-horizon-py27
        - cross-horizon-py35
        - cross-keystone-py27
        - cross-keystone-py35
        - cross-neutron-py27
        - cross-neutron-py35
        - cross-nova-py27
        - cross-nova-py35:
            files: ^upper-constraints.txt$
        - cross-nova-functional
        - cross-osc-build-sphinx-docs
        - cross-swift-py27
        - cross-swift-py35
        - openstack-tox-py36
        - requirements-integration
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - neutron-grenade:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    post:
      jobs:
        - publish-loci-requirements
    experimental:
      jobs:
        - legacy-tempest-dsvm-neutron-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-neutron-full-opensuse-423:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

