- project:
    name: openstack/requirements
    check:
      jobs:
        - openstack-tox-validate
        - cross-cinder-py27:
            files: ^upper-constraints.txt$
        - cross-cinder-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-glance-py27:
            files: ^upper-constraints.txt$
        - cross-glance-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-horizon-py27:
            files: ^upper-constraints.txt$
        - cross-horizon-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-keystone-py27:
            files: ^upper-constraints.txt$
        - cross-keystone-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-neutron-py27:
            files: ^upper-constraints.txt$
        - cross-neutron-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-py27:
            files: ^upper-constraints.txt$
        - cross-nova-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-functional:
            files: ^upper-constraints.txt$
        - cross-swift-py27:
            files: ^upper-constraints.txt$
        - cross-swift-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
    gate:
      queue: integrated
      jobs:
        - openstack-tox-validate
        - cross-cinder-py27:
            files: ^upper-constraints.txt$
        - cross-cinder-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-glance-py27:
            files: ^upper-constraints.txt$
        - cross-glance-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-horizon-py27:
            files: ^upper-constraints.txt$
        - cross-horizon-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-keystone-py27:
            files: ^upper-constraints.txt$
        - cross-keystone-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-neutron-py27:
            files: ^upper-constraints.txt$
        - cross-neutron-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-py27:
            files: ^upper-constraints.txt$
        - cross-nova-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
        - cross-nova-functional:
            files: ^upper-constraints.txt$
        - cross-swift-py27:
            files: ^upper-constraints.txt$
        - cross-swift-py35:
            branches: ^(?!stable/(newton|ocata)).*$
            files: ^upper-constraints.txt$
