- project:
    vars:
      # TODO(gmann): Unpin tox once all the projects which requirements repo runs
      # checks for are fixed for tox4. Current failure of projects can be found
      # in this patch: https://review.opendev.org/c/openstack/requirements/+/868922
      ensure_tox_version: '<4'
    templates:
      - openstack-python3-jobs
    check:
      jobs:
        - build-wheel-cache-centos-7:
            files:
              - bindep.txt
        - build-wheel-cache-centos-8-stream:
            files:
              - bindep.txt
        - build-wheel-cache-debian-buster:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-xenial:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-focal:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-jammy:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-bindep:
            voting: false
        - requirements-tox-py38-check-uc
        - requirements-tox-py39-check-uc
        - requirements-tox-validate-projects:
            voting: false
        - cross-aodh-py310
        - cross-barbican-py310
        - cross-ceilometer-py310
        - cross-cinder-py310
        - cross-designate-py310
        - cross-glance-py310
        - cross-heat-py310
        - cross-horizon-py310
        - cross-horizon-npm
        - cross-ironic-py310
        - cross-keystone-py310
        - cross-kuryr-py310
        - cross-manila-py310
        - cross-masakari-py310
        - cross-mistral-py310
        - cross-neutron-py310
        - dnm-cross-networking-bgpvpn-py310
        - dnm-cross-networking-bagpipe-py310
        - dnm-cross-networking-odl-py310
        - dnm-cross-networking-sfc-py310
        - dnm-cross-neutron-dynamic-routing-py310
        - dnm-cross-neutron-fwaas-py310
        - dnm-cross-neutron-vpnaas-py310
        - dnm-cross-tap-as-a-service-py310
        - cross-nova-py310
        - cross-placement-py310
        - cross-osvif-py3
        - cross-nova-functional
        - cross-placement-functional-py310
        - cross-octavia-py310
        - cross-osc-tox-docs
        - cross-swift-py38
        - openstacksdk-functional-devstack
        - tempest-full-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    check-arm64:
      jobs:
        - requirements-tox-py38-check-uc-aarch64:
            files:
              - bindep.txt
              - upper-constraints.txt
        - build-wheel-cache-centos-8-stream-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-debian-buster-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-bionic-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-focal-arm64:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-jammy-arm64:
            files:
              - bindep.txt
    gate:
      jobs:
        - build-wheel-cache-centos-7:
            files:
              - bindep.txt
        - build-wheel-cache-centos-8-stream:
            files:
              - bindep.txt
        - build-wheel-cache-debian-buster:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-xenial:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-bionic:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-focal:
            files:
              - bindep.txt
        - build-wheel-cache-ubuntu-jammy:
            files:
              - bindep.txt
        - openstack-tox-validate
        - requirements-tox-babel
        - requirements-tox-py38-check-uc
        - requirements-tox-py39-check-uc
        - cross-cinder-py310
        - cross-designate-py310
        - cross-glance-py310
        - cross-heat-py310
        - cross-horizon-py310
        - cross-horizon-npm
        - cross-ironic-py310
        - cross-keystone-py310
        - cross-kuryr-py310
        - cross-manila-py310
        - cross-masakari-py310
        - cross-neutron-py310
        - cross-nova-py310:
            files: ^upper-constraints.txt$
        - cross-placement-py310:
            files: ^upper-constraints.txt$
        - cross-osvif-py3
        - cross-nova-functional
        - cross-placement-functional-py310
        - cross-octavia-py310
        - cross-osc-tox-docs
        - cross-swift-py38
        - openstacksdk-functional-devstack
        - tempest-full-py3:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    experimental:
      jobs:
        - tempest-pg-full:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
