- hosts: all
  tasks:
    - name: Build and install librdkafka 1.4.0+
      block:
        - name: Install librdkafka build dependencies
          apt:
            name:
              - liblz4-dev
              - libsasl2-dev
              - libssl-dev
              - libzstd-dev
              - python3
              - zlib1g-dev
              - debhelper
              - devscripts
              - wget
              - build-essential
            state: present
            install_recommends: no
          become: true

        - name: Fetch librdkafka from Debian 'testing'
          command: "dget -u http://deb.debian.org/debian/pool/main/libr/librdkafka/librdkafka_1.4.2-1.dsc"
          args:
            chdir: "/tmp/"

          # NOTE(hrw): use '-d' to skip 'error: Unmet build dependencies: debhelper-compat (= 13)'
        - name: Build librdkafka package
          command: "dpkg-buildpackage -b -d"
          args:
            chdir: "/tmp/librdkafka-1.4.2/"

        - name: Install librdkafka packages
          apt:
            deb:
              - "/tmp/librdkafka++1_1.4.2-1_arm64.deb"
              - "/tmp/librdkafka-dev_1.4.2-1_arm64.deb"
              - "/tmp/librdkafka1_1.4.2-1_arm64.deb"
          become: true
