- hosts: all
  tasks:
    - name: Run requirements check script
      # Use command instead of script since Zuul gets output with command
      # into job-output.txt file.
      # Command expects the file to be at the other system, use proper path:
      command: "{{ zuul._projects['git.openstack.org/openstack/requirements'].src_dir }}/playbooks/files/project-requirements-change.py {{ zuul.project.src_dir }} {{ zuul.branch }}"
